#############################################################################
# Makefile for building: best_ora_ide
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  best_ora_ide.pro
# Template: subdirs
# Command: C:\Qt\5.8\mingw53_32\bin\qmake.exe -o Makefile best_ora_ide.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.8\mingw53_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-source \
		sub-tests


sub-source-qmake_all:  FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd source\ && $(MAKE) -f Makefile qmake_all
sub-source: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-source-make_first-ordered: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-source-make_first: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-source-all-ordered: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-source-all: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-source-clean-ordered: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-source-clean: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-source-distclean-ordered: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-source-distclean: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-source-install_subtargets-ordered: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-source-install_subtargets: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-source-uninstall_subtargets-ordered: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-source-uninstall_subtargets: FORCE
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-source-qmake_all FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd tests\ && $(MAKE) -f Makefile qmake_all
sub-tests: src FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-tests-make_first-ordered: sub-source-make_first-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-tests-make_first: src-make_first FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-tests-all-ordered: sub-source-all-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-tests-all: src-all FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-tests-clean-ordered: sub-source-clean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-tests-clean: src-clean FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-tests-distclean-ordered: sub-source-distclean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-tests-distclean: src-distclean FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets-ordered: sub-source-install_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-tests-install_subtargets: src-install_subtargets FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets-ordered: sub-source-uninstall_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-tests-uninstall_subtargets: src-uninstall_subtargets FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: best_ora_ide.pro C:/Qt/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf C:/Qt/5.8/mingw53_32/mkspecs/features/spec_pre.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/qdevice.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/features/device_config.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/common/angle.conf \
		C:/Qt/5.8/mingw53_32/mkspecs/qconfig.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.8/mingw53_32/mkspecs/features/qt_functions.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/qt_config.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/toolchain.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/default_pre.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/resolve_config.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/default_post.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/qml_debug.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/win32/rtti.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/precompile_header.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/warn_on.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/qmake_use.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/file_copies.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/win32/windows.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/exceptions.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/yacc.prf \
		C:/Qt/5.8/mingw53_32/mkspecs/features/lex.prf \
		best_ora_ide.pro
	$(QMAKE) -o Makefile best_ora_ide.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
C:/Qt/5.8/mingw53_32/mkspecs/features/spec_pre.prf:
C:/Qt/5.8/mingw53_32/mkspecs/qdevice.pri:
C:/Qt/5.8/mingw53_32/mkspecs/features/device_config.prf:
C:/Qt/5.8/mingw53_32/mkspecs/common/angle.conf:
C:/Qt/5.8/mingw53_32/mkspecs/qconfig.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_accessibility_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_charts_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_clucene_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_egl_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gamepad_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_location_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_purchasing_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_script_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scripttools_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_texttospeech_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_winextras_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/Qt/5.8/mingw53_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/Qt/5.8/mingw53_32/mkspecs/features/qt_functions.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/qt_config.prf:
C:/Qt/5.8/mingw53_32/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.8/mingw53_32/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/toolchain.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/default_pre.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/resolve_config.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/default_post.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/qml_debug.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/win32/rtti.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/precompile_header.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/warn_on.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/qmake_use.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/file_copies.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/win32/windows.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/testcase_targets.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/exceptions.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/yacc.prf:
C:/Qt/5.8/mingw53_32/mkspecs/features/lex.prf:
best_ora_ide.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile best_ora_ide.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-source-qmake_all sub-tests-qmake_all FORCE

make_first: sub-source-make_first-ordered sub-tests-make_first-ordered  FORCE
all: sub-source-all-ordered sub-tests-all-ordered  FORCE
clean: sub-source-clean-ordered sub-tests-clean-ordered  FORCE
distclean: sub-source-distclean-ordered sub-tests-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-source-install_subtargets-ordered sub-tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-source-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered FORCE

sub-source-debug_ordered:
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-tests-debug_ordered: sub-source-debug_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-source-debug_ordered sub-tests-debug_ordered

sub-source-release_ordered:
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-tests-release_ordered: sub-source-release_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-source-release_ordered sub-tests-release_ordered

sub-source-check_ordered:
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-tests-check_ordered: sub-source-check_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-source-check_ordered sub-tests-check_ordered

sub-source-benchmark_ordered:
	@if not exist source\ mkdir source\ & if not exist source\ exit 1
	cd source\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\source\source.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-tests-benchmark_ordered: sub-source-benchmark_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\documents\GitHub\best_ora_ide\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-source-benchmark_ordered sub-tests-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

